### ISSUE TITLE
GroovyVerticle fails to run

### ISSUE THREAD

**Issue by tsegismont** [cescoffier/vertx-microservices-workshop#31]
```
GRAVE: No signature of method: static io.vertx.servicediscovery.types.MessageSource.getConsumer() is applicable for argument types: (io.vertx.servicediscovery.impl.DiscoveryImpl, java.util.LinkedHashMap, io.vertx.core.impl.FutureImpl) values: [io.vertx.servicediscovery.impl.DiscoveryImpl@1c36f9, [name:market-data], ...]
groovy.lang.MissingMethodException: No signature of method: static io.vertx.servicediscovery.types.MessageSource.getConsumer() is applicable for argument types: (io.vertx.servicediscovery.impl.DiscoveryImpl, java.util.LinkedHashMap, io.vertx.core.impl.FutureImpl) values: [io.vertx.servicediscovery.impl.DiscoveryImpl@1c36f9, [name:market-data], ...]
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1503)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1489)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at GroovyCompulsiveTraderVerticle.run(GroovyCompulsiveTraderVerticle.groovy:22)
	at io.vertx.lang.groovy.ScriptVerticle.start(ScriptVerticle.java:64)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cescoffier** [comment]
Interesting catch, I believe the "json" map is not right...

**Comment by hakdogan** [comment]
Hi @cescoffier 

I'm getting the same exception.

```
groovy.lang.MissingMethodException: No signature of method: static io.vertx.servicediscovery.types.MessageSource.getConsumer() is applicable for argument types: (io.vertx.servicediscovery.impl.DiscoveryImpl, java.util.LinkedHashMap, io.vertx.core.impl.FutureImpl) values: [io.vertx.servicediscovery.impl.DiscoveryImpl@2e412821, [name:market-data], ...]
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1503)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1489)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
        at GroovyCompulsiveTraderVerticle.run(GroovyCompulsiveTraderVerticle.groovy:27)
        at io.vertx.lang.groovy.ScriptVerticle.start(ScriptVerticle.java:64)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by deepbreath** [comment]
haha!  follow doc  file you will be know what happen

**Comment by deepbreath** [comment]
> Interesting catch, I believe the "json" map is not right...

yeah~ l like that doc file,thanks
