### ISSUE TITLE
io.vertx.core.impl.ContextImpl: Unsupported service type message-source error for multiple Javatrader

### ISSUE THREAD

**Issue by nguyentu1602** [cescoffier/vertx-microservices-workshop#4]
https://github.com/cescoffier/vertx-microservices-workshop/blob/master/solution/compulsive-traders/src/main/java/io/vertx/workshop/trader/impl/JavaCompulsiveTraderVerticle.java

Hi Clement, I followed your training, and when I deployed the JavaCompulsiveTraderVerticle, I got the below error if I deploy more than one of them. This error only shows up for multiple JavaTraders, not for multiple GroovyTraders.

I did a clean checkout and try to use your solution, the same error still persists. Could you please take a look?

INFO: Discovery importer io.vertx.servicediscovery.docker.DockerLinksServiceImporter@660c7311 started

Jun 25, 2016 8:13:31 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: Unsupported service type message-source
	at io.vertx.servicediscovery.impl.ServiceTypes.get(ServiceTypes.java:43)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getReferenceWithConfiguration(DiscoveryImpl.java:108)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getReference(DiscoveryImpl.java:103)
	at io.vertx.servicediscovery.types.MessageSource.lambda$getConsumer$0(MessageSource.java:136)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$getRecord$6(DiscoveryImpl.java:275)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$getRecords$4(DefaultServiceDiscoveryBackend.java:100)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$1(ContextImpl.java:315)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cescoffier** [comment]
Just fixed it in the service discovery project:
https://github.com/vert-x3/vertx-service-discovery/issues/37

Thanks for reporting !

**Comment by nguyentu1602** [comment]
awesome. Great tutorial btw. Thanks a lot.

**Comment by cescoffier** [comment]
The issue has been fixed, the the Vert.x version updated.
